name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: automerge-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge labeled PRs once checks are green
        uses: pascalgn/automerge-action@a4ba3817b71522d026f0edbb4c3de3bc22f8b4fc # v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: automerge
          MERGE_DELETE_BRANCH: "true"
